namespace slap.Things.Society;

// Disclaimer: these locations were generated by AI (Claude 3.5 Sonnet), so their reliability may not be guaranteed.
public class CommonLocations
{
    public enum CommonCities
    {
        NewYork,
        London,
        Tokyo,
        Paris,
        Sydney,
        Dubai,
        Singapore,
        LosAngeles,
        Chicago,
        Toronto
    }

    public static readonly Dictionary<CommonCities, Location> CityMap = new()
    {
        {
            CommonCities.NewYork,
            new Location(
                "New York City",
                "The Big Apple, largest city in the United States",
                40.7127281,
                -74.0060152
            )
        },
        {
            CommonCities.London,
            new Location(
                "London",
                "Capital of England and the United Kingdom",
                51.5073219,
                -0.1276474
            )
        },
        {
            CommonCities.Tokyo,
            new Location(
                "Tokyo",
                "Capital of Japan, largest metropolitan area in the world",
                35.6761919,
                139.6503106
            )
        },
        {
            CommonCities.Paris,
            new Location(
                "Paris",
                "City of Light, capital of France",
                48.8566969,
                2.3514616
            )
        },
        {
            CommonCities.Sydney,
            new Location(
                "Sydney",
                "Largest city in Australia, home to the Opera House",
                -33.8688197,
                151.2092955
            )
        },
        {
            CommonCities.Dubai,
            new Location(
                "Dubai",
                "Largest city in UAE, known for modern architecture",
                25.2048493,
                55.2707828
            )
        },
        {
            CommonCities.Singapore,
            new Location(
                "Singapore",
                "Island city-state in Southeast Asia",
                1.3521456,
                103.8198374
            )
        },
        {
            CommonCities.LosAngeles,
            new Location(
                "Los Angeles",
                "Entertainment capital of the world",
                34.0522342,
                -118.2436849
            )
        },
        {
            CommonCities.Chicago,
            new Location(
                "Chicago",
                "The Windy City, third-largest US city",
                41.8781136,
                -87.6297982
            )
        },
        {
            CommonCities.Toronto,
            new Location(
                "Toronto",
                "Largest city in Canada",
                43.6534817,
                -79.3839347
            )
        }
    };
}
